### ISSUE TITLE
Crystal 0.31.0+, 0.32.0+ compatibility

### ISSUE THREAD

**Issue by daliborfilus** [nats-io/nats.cr#7]
1) A patch is required for new modulo function/method.
The patch is provided by @Tails in commit https://github.com/Tails/nats.cr/commit/d0e6cf570ca2d1f1c54ff7c8c25fd06fec605fbc.
An addition of `require "big"` is also required in nuid.cr.

Further patching is required for connection.cr, see https://github.com/NoICE/nats.cr/commit/616e96a0f576969a16f19348460f6618bf2d6db0.

2) Crystal 0.31.0 introduced many changes to Channel, removing Channel::Buffered in the process.
(https://crystal-lang.org/api/0.31.0/Channel.html)
The new implementation doesn't have #empty? method, which is used heavily in connection.cr.
If calls to `@flush#empty?` are removed, the connection deadlocks:

```
Unhandled exception: Attempt to lock a mutex recursively (deadlock) (Exception)
  from /usr/share/crystal/src/mutex.cr:44:21 in 'lock'
  from lib/nats/src/nats/connection.cr:132:5 in 'flush_outbound'
  from lib/nats/src/nats/connection.cr:376:9 in 'close'
```

Can be seen via nats-pub binary:
```
$ ./bin/nats-pub -s localhost subject test
Published [subject] : 'test'
Error running at_exit handler: Attempt to lock a mutex recursively (deadlock)
```

I can't find any replacement for this, as far I can see.

**Comment by daliborfilus** [comment]
Looks like the above error message was caused solely by `#close` method, which did `synchronize` around `flush_outbound`, which also does `synchronize`. Moving the `flush_outbound` call outside of `synchronize` solved the second issue. (See https://github.com/NoICE/nats.cr/commit/265489b0203c28ed98143f246e9a71254a874416.) Without calls to `@flush.empty?` we are now doing multiple flushes, but that shouldn't be too much of an issue. Right?

**Comment by derekcollison** [comment]
We are close to having everything working for current version.

Apologies for the delay.

**Comment by thelinuxlich** [comment]
Shouldn't this be closed?

**Comment by derekcollison** [comment]
Yes.
